### ISSUE TITLE
Variant description

### ISSUE THREAD

**Issue by flor-rovere** [flor-rovere/UNR-EC-2017-g06#2]
- Provide a document with an elaborated description of the assigned variants. 

- Make focus on the new functionalities to be incorporated into the system under development

- Provide examples to illustrate these new functionalities

- Upload the document into your GitHub repo.

**Comment by flor-rovere** [comment]
Started at 18.00, finished at 19.25

**Comment by acapozucca** [comment]
SMS based auth variant:
No es un poco inseguro que cada vez que el usr intenta autenticar tenga que ingresar el celular donde quiere recibir el token? No sería mejor que el celular sea un parámetro del perfil de usuario? Tal vez se le podría dar la opción de cambiarlo (una vez que haya autenticado).

**Comment by acapozucca** [comment]
Coordinator accounts variant:
La política de reasignación de alertas y crisis debería ser más flexible y elaborada que el orden alfabético. Por ejemplo, el coordinador puede ser seleccionado por el administrador, o el que menos crisis se encuntra administrando en ese preciso momento.
Se tendría que aclarar mejor cómo se computan las "recomendaciones sobre los coordinadores a inhabilitar". Habría que analizar el caso en que solo queda o hay un coordinador disponible en el sistema.
